theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
logo: blob/master/images/ThinkMachine_logo_fenix.svg
title: Think Machine 4E
description: Fading Suns 4E character sheet generator based on Java.
author: 
  name: Jorge Hortelano
  email: softwaremagico@gmail.com

image:
  path: blob/master/images/ThinkMachine_logo_fenix.png
